<template>
  <v-dialog
    v-model="dialog"
    attach="#walletDialogsParent"
    content-class="uiPopup with-overflow not-draggable"
    class="walletSettingsModal"
    width="700px"
    max-width="100vw"
    persistent>
    <v-card class="elevation-12">
      <div class="popupHeader ClearFix">
        <a
          class="uiIconClose pull-right"
          aria-hidden="true"
          @click="dialog = false"></a> <span class="PopupTitle popupTitle">
            {{ $t('exoplatform.wallet.title.security') }}
          </span>
      </div>
      <v-card-text v-if="loading || appLoading" class="text-xs-center pt-0">
        <v-progress-circular
          color="primary"
          class="mb-2"
          indeterminate />
      </v-card-text>
      <v-card-text v-show="!loading && !appLoading" class="pt-0">
        <div v-if="error && !loading" class="alert alert-error v-content">
          <i class="uiIconError"></i>{{ error }}
        </div>
        <v-flex>
          <v-tabs
            v-if="selectedTab !== 'security'"
            ref="settingsTabs"
            v-model="selectedTab"
            class="pl-3 pr-3">
            <v-tabs-slider />
            <v-tab
              key="security"
              href="#security">
              {{ $t('exoplatform.wallet.title.security') }}
            </v-tab>
            <v-tab
              v-if="selectedTab === 'keys'"
              key="keys"
              href="#keys">
              {{ $t('exoplatform.wallet.title.manageKeys') }}
            </v-tab>
          </v-tabs>
          <v-tabs-items v-model="selectedTab">
            <v-tab-item
              id="security"
              value="security">
              <settings-security-tab
                ref="securityTab"
                :wallet-address="walletAddress"
                :is-space="isSpace"
                @settings-changed="$emit('settings-changed')"
                @manage-keys="selectedTab = 'keys'" />
            </v-tab-item>
            <v-tab-item
              id="keys"
              value="keys">
              <v-card>
                <v-card-text v-if="walletAddress" class="pb-0">
                  <qr-code
                    ref="qrCode"
                    :to="walletAddress"
                    :title="$t('exoplatform.wallet.title.addressQRCode')"
                    :information="$t('exoplatform.wallet.info.addressQRCode')" />
                  <div class="text-xs-center">
                    <wallet-address :value="walletAddress" :allow-edit="false" />
                  </div>
                </v-card-text>
                <v-card-text v-if="browserWalletExists" class="text-xs-center pb-0">
                  <backup-modal
                    ref="walletBackupModal"
                    :display-complete-message="false"
                    @backed-up="
                      $emit('backed-up');
                      refreshFromSettings();
                    " />
                </v-card-text>
                <v-card-text class="text-xs-center">
                  <import-key-modal
                    ref="walletImportKeyModal"
                    :is-space="isSpace"
                    :wallet-address="walletAddress"
                    @configured="
                      $emit('settings-changed');
                      refreshFromSettings();
                    " />
                </v-card-text>
              </v-card>
            </v-tab-item>
          </v-tabs-items>
        </v-flex>
      </v-card-text>
      <v-divider />
      <v-card-actions>
        <v-spacer />
        <button
          :disabled="loading"
          class="btn"
          @click="dialog = false">
          {{ $t('exoplatform.wallet.button.close') }}
        </button>
        <v-spacer />
      </v-card-actions>
    </v-card>
  </v-dialog>
</template>

<script>
import SettingsSecurityTab from './SettingsSecurityTab.vue';

export default {
  components: {
    SettingsSecurityTab,
  },
  props: {
    title: {
      type: String,
      default: function() {
        return null;
      },
    },
    appLoading: {
      type: Boolean,
      default: function() {
        return false;
      },
    },
    isSpace: {
      type: Boolean,
      default: function() {
        return false;
      },
    },
    open: {
      type: Boolean,
      default: function() {
        return false;
      },
    },
    displayResetOption: {
      type: Boolean,
      default: function() {
        return false;
      },
    },
  },
  data() {
    return {
      settings: false,
      loading: false,
      dialog: false,
      error: null,
      walletAddress: null,
      selectedTab: null,
      accountType: 0,
      autoGeneratedPassword: false,
      hasKeyOnServerSide: false,
      browserWalletExists: false,
    };
  },
  watch: {
    walletAddress() {
      if (this.walletAddress) {
        this.$nextTick(() => {
          this.$refs.qrCode.computeCanvas();
        });
      }
    },
    appLoading() {
      if (!this.appLoading) {
        this.refreshFromSettings();
      }
    },
    open() {
      if (this.open) {
        this.error = null;
        this.settings = window.walletSettings || {wallet: {}, userPreferences: {}};
        this.walletAddress = this.settings.wallet.address;

        // Workaround to display slider on first popin open
        if (this.$refs.settingsTabs) {
          this.$refs.settingsTabs.callSlider();
        }

        this.dialog = true;
        this.$nextTick(() => {
          this.refreshFromSettings();
          this.walletUtils.setDraggable();
        });
      }
    },
    dialog() {
      if (!this.dialog) {
        this.$emit('close');
      }
    },
  },
  methods: {
    refreshFromSettings() {
      this.settings = window.walletSettings || {wallet: {}, userPreferences: {}};
      this.hasKeyOnServerSide = this.settings.userPreferences && this.settings.userPreferences.hasKeyOnServerSide;
      this.autoGeneratedPassword = this.settings.userPreferences && this.settings.userPreferences.autoGenerated;
      this.browserWalletExists = this.settings.userPreferences && this.settings.browserWalletExists;
      if (this.$refs.securityTab) {
        this.$refs.securityTab.init();
      }
    },
    removeServerSideBackup() {
      return this.walletUtils.removeServerSideBackup(this.walletAddress)
        .then((removed) => {
          if (removed) {
            this.$emit('settings-changed');
          }
          return this.$nextTick();
        })
        .then(() => {
          this.refreshFromSettings();
        })
        .catch(e => {
          this.error = String(e);
        });
    },
  },
};
</script>
