<template>
  <v-dialog
    id="walletBackupModal" 
    v-model="dialog"
    :disabled="disabled"
    attach="#walletDialogsParent"
    class="fixLinkHeight"
    content-class="uiPopup with-overflow"
    width="500px"
    max-width="100vw"
    persistent
    @keydown.esc="dialog = false">
    <a
      v-if="!noButton"
      slot="activator"
      href="javascript:void(0);"
      @click="dialog = true">
      {{ $t('exoplatform.wallet.title.backupWalletModal') }}
    </a>
    <v-card class="elevation-12">
      <div class="popupHeader ClearFix" draggable="true">
        <a
          class="uiIconClose pull-right"
          aria-hidden="true"
          @click="dialog = false"></a> <span class="PopupTitle popupTitle">
            {{ $t('exoplatform.wallet.button.backupWallet') }}
          </span>
      </div>
      <v-card-text>
        <div v-if="error" class="alert alert-error">
          <i class="uiIconError"></i> {{ error }}
        </div>

        <div
          v-if="displayCompleteMessage"
          id="walletBackupDetailedWarning"
          class="alert alert-warning v-content">
          <p>
            <i class="uiIconWarning"></i>
            {{ $t('exoplatform.wallet.info.backupWalletPart1') }}. <br>
            {{ $t('exoplatform.wallet.info.backupWalletPart2') }}: <br>
            - {{ $t('exoplatform.wallet.info.backupWalletPart3') }} <br>
            - {{ $t('exoplatform.wallet.info.backupWalletPart4') }}
          </p>
          <p>
            {{ $t('exoplatform.wallet.info.backupWalletPart5') }}. <br>
            {{ $t('exoplatform.wallet.info.backupWalletPart6') }}, <strong>
              {{ $t('exoplatform.wallet.info.backupWalletPart7') }}
            </strong>.
          </p>
        </div>
        <div 
          v-else 
          id="walletBackupSimpleWarning"
          class="alert alert-warning v-content">
          <p>
            <i class="uiIconWarning"></i>
            {{ $t('exoplatform.wallet.info.backupWalletPart8') }}. <br>
            {{ $t('exoplatform.wallet.info.backupWalletPart9') }}, <strong>
              {{ $t('exoplatform.wallet.info.backupWalletPart10') }}
            </strong>.
          </p>
        </div>

        <v-form
          ref="form"
          @submit="
            $event.preventDefault();
            $event.stopPropagation();
          ">
          <v-text-field
            v-if="dialog && !autoGeneratedPassword && !walletPrivateKey"
            v-model="walletPassword"
            :append-icon="walletPasswordShow ? 'visibility_off' : 'visibility'"
            :rules="[rules.min]"
            :type="walletPasswordShow ? 'text' : 'password'"
            name="walletPassword"
            label="Current wallet password"
            placeholder="Enter your current wallet password"
            counter
            autocomplete="current-passord"
            autofocus
            @click:append="walletPasswordShow = !walletPasswordShow" />
        </v-form>
      </v-card-text>
      <v-card-text v-if="walletPrivateKey" class="text-xs-center">
        <code v-text="walletPrivateKey"></code>
      </v-card-text>
      <v-card-actions>
        <v-spacer />
        <button
          v-if="walletPrivateKey"
          class="btn btn-primary mr-1"
          @click="walletBackedUp">
          {{ $t('exoplatform.wallet.button.backedUp') }}!
        </button>
        <button
          v-if="!walletPrivateKey"
          :disabled="loading"
          class="btn btn-primary mr-1"
          @click="showPrivateKey">
          {{ $t('exoplatform.wallet.button.displayPrivateKey') }}!
        </button> <button
          v-if="!walletPrivateKey"
          :disabled="loading"
          class="btn"
          @click="dialog = false">
          {{ $t('exoplatform.wallet.button.close') }}!
        </button>
        <v-spacer />
      </v-card-actions>
    </v-card>
  </v-dialog>
</template>

<script>

import {setDraggable, unlockBrowserWallet, lockBrowserWallet, getCurrentBrowserWallet, hashCode, setWalletBackedUp} from '../js/WalletUtils.js';

export default {
  props: {
    displayCompleteMessage: {
      type: Boolean,
      default: function() {
        return false;
      },
    },
    noButton: {
      type: Boolean,
      default: function() {
        return false;
      },
    },
  },
  data() {
    return {
      dialog: false,
      error: null,
      walletPassword: '',
      walletPasswordShow: false,
      walletPrivateKey: null,
      autoGeneratedPassword: false,
      loading: false,
      rules: {
        min: (v) => (v && v.length >= 8) || this.$t('exoplatform.wallet.warning.atLeast8Chars'),
      },
    };
  },
  watch: {
    dialog() {
      if (this.dialog) {
        if (this.$refs.form) {
          this.$refs.form.reset();
        }
        this.init();
        this.$nextTick(() => {
          setDraggable();
        });
      }
    },
  },
  created() {
    this.init();
  },
  methods: {
    init() {
      this.error = null;
      this.walletPrivateKey = null;
      this.walletPassword = '';
      this.walletPasswordShow = false;
      this.autoGeneratedPassword = window.walletSettings.userPreferences.autoGenerated;
      this.loading = false;
    },
    walletBackedUp() {
      this.error = null;
      setWalletBackedUp()
        .then(wallet => {
          this.$emit('backed-up');
          this.dialog = false;
        }).catch((error) => {
          this.error = String(error);
        })
        .finally(() => {
          this.loading = false;
        });
    },
    showPrivateKey() {
      this.error = null;
      if (!this.$refs.form.validate()) {
        return;
      }
      this.loading = true;
      window.setTimeout(this.unlockBrowserWallet, 200);
    },
    unlockBrowserWallet() {
      const unlocked = unlockBrowserWallet(this.autoGeneratedPassword ? window.walletSettings.userP : hashCode(this.walletPassword));
      try {
        if (unlocked) {
          const wallet = getCurrentBrowserWallet();
          if (!wallet || !wallet.privateKey) {
            this.error = this.$t('exoplatform.wallet.error.walletNotFound');
            return;
          }
          this.loading = false;
          this.walletPrivateKey = wallet.privateKey;
        } else if (this.autoGeneratedPassword) {
          this.error = this.$t('exoplatform.wallet.error.errorRetrievingPrivateKey');
        } else {
          this.error = this.$t('exoplatform.wallet.warning.wrongPassword');
        }
      } finally {
        this.loading = false;
        if (unlocked) {
          lockBrowserWallet();
        }
      }
    },
  },
};
</script>
