<template>
  <v-flex class="text-xs-center white">
    <div
      v-show="!loading"
      id="walletBrowserSetup"
      class="mt-3 mb-3">
      <template v-if="walletAddress">
        <wallet-import-key-modal
          ref="walletImportKeyModal"
          :is-space="isSpace"
          :wallet-address="walletAddress"
          @configured="$emit('configured')" />
        <div>
          Or
        </div>
        <a href="javascript:void(0);" @click="switchToMetamask">
          Use metamask
        </a>
      </template>
      <template v-else>
        <v-form ref="form">
          <v-text-field
            v-if="!loading"
            v-model="walletPassword"
            :append-icon="walletPasswordShow ? 'visibility_off' : 'visibility'"
            :rules="[rules.min]"
            :type="walletPasswordShow ? 'text' : 'password'"
            :disabled="loading || loadingWalletBrowser"
            :autofocus="autoGeneratedPassword"
            name="walletPassword"
            label="Wallet password"
            placeholder="Set a wallet password"
            counter
            required
            autocomplete="new-passord"
            @click:append="walletPasswordShow = !walletPasswordShow" />
        </v-form>
        <button
          :disabled="loadingWalletBrowser"
          class="btn btn-primary"
          @click="createWallet()">
          Create new wallet
        </button>
      </template>
    </div>
  </v-flex>
</template>

<script>
import WalletImportKeyModal from './WalletImportKeyModal.vue';

import {enableMetamask, initEmptyWeb3Instance, saveBrowserWalletInstance} from '../js/WalletUtils.js';

export default {
  components: {
    WalletImportKeyModal,
  },
  props: {
    isSpace: {
      type: Boolean,
      default: function() {
        return false;
      },
    },
    isSpaceAdministrator: {
      type: Boolean,
      default: function() {
        return false;
      },
    },
    isAdministration: {
      type: Boolean,
      default: function() {
        return false;
      },
    },
    loading: {
      type: Boolean,
      default: function() {
        return false;
      },
    },
    refreshIndex: {
      type: Number,
      default: function() {
        return 0;
      },
    },
  },
  data() {
    return {
      walletAddress: null,
      walletPassword: null,
      walletPasswordShow: null,
      loadingWalletBrowser: false,
      rules: {
        min: (v) => (v && v.length >= 8) || 'At least 8 characters',
      },
    };
  },
  watch: {
    refreshIndex(newValue, oldValue) {
      if (newValue > oldValue) {
        this.$nextTick(this.init);
      }
    },
  },
  created() {
    this.init();
  },
  methods: {
    init() {
      this.walletPassword = null;
      this.loadingWalletBrowser = false;
      if (!window.localWeb3) {
        initEmptyWeb3Instance();
      }
      if (window.walletSettings && window.walletSettings.userPreferences) {
        this.walletAddress = window.walletSettings.userPreferences.walletAddress;
      }
    },
    createWallet() {
      if (!this.$refs.form.validate()) {
        return;
      }
      this.loadingWalletBrowser = true;

      // Use set timeout to allow refresh UI by disabling button before processing
      window.setTimeout(this.createWalletInstance, 200);
    },
    createWalletInstance() {
      const entropy = this.walletPassword + Math.random();
      const wallet = window.localWeb3.eth.accounts.wallet.create(1, entropy);
      const walletAddress = wallet && wallet[0] && wallet[0].address;
      if (!walletAddress) {
        console.debug('saveBrowserWalletInstance method - error: no address in created wallet', wallet);
        this.$emit('error', 'Error saving creating new Wallet');
        return;
      }
      return saveBrowserWalletInstance(wallet[0], this.walletPassword, this.isSpace)
        .then(() => {
          this.$emit('configured');
          this.loadingWalletBrowser = false;
        })
        .catch((e) => {
          console.debug('saveBrowserWalletInstance method - error', e);
          this.$emit('error', 'Error saving new Wallet address');
          this.loadingWalletBrowser = false;
        });
    },
    switchToMetamask() {
      enableMetamask(this.isSpace);
      this.$emit('configured');
    },
  },
};
</script>
